Feature: Skip double formatting
atextor/turtle-formatter pull request #31
Opened 2024-09-16 12:10 UTC by fkleedorfer

Provides a new style property, 'skipDoubleFormatting' that causes all double values to be formatted as they are in the input.

(also adds a main method to the TurtleFormatter for easy testing)

closes #30

2024-09-17 04:39 UTC, atextor requested changes

2024-09-17 04:39 UTC, atextor commented on src/main/java/de/atextor/turtle/formatter/TurtleFormatter.java
> +        } else {
Remove this `else` and unindent the following lines

2024-09-17 04:39 UTC, atextor commented on src/main/java/de/atextor/turtle/formatter/TurtleFormatter.java
> +    }
Although I understand the reason and intention behind this, please remove the `main` method. TurtleFormatter is used as a library also in contexts where another `main` method is explicitly undesirable.
(But https://github.com/atextor/owl-cli/issues/20 will solve this problem! turtle-formatter will be a module in the overall command line tool, so you'll have an entry point for convenient local testing)

2024-09-20 04:49 UTC, atextor approved these changes
Looks good to me!

2024-09-20 04:49 UTC, merged

2024-09-21 06:20 UTC, fkleedorfer commented
Again, a release of this will be greatly appreaciated. (sorry to be pushy about this)

2024-09-21 14:39 UTC, atextor commented
> Again, a release of this will be greatly appreaciated. (sorry to be pushy about this)

Yes, I'm aware :)
It's released now as [1.2.13](https://github.com/atextor/turtle-formatter/releases/tag/v1.2.13).